### ISSUE TITLE
Empty legends frames are annoying

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [IRFM/divHretention#41]
The class plot_along_divertor should integrate (or not integrate) legends and labels.

**Screenshots**

![image](https://user-images.githubusercontent.com/40028739/122579166-eef81c80-d054-11eb-8028-143ad84258a7.png)

**Comment by jhdark** [comment]
@RemDelaporteMathurin 

Do you have a sample script to reproduce this figure?

**Comment by RemDelaporteMathurin** [comment]
Running this MWE at the root directory reproduces the issue:
```python
from divHretention import plot_along_divertor
import matplotlib.pyplot as plt
filename = "examples/ITER/2399/2399_outer_target.csv"
plot_along_divertor(
    filenames=[filename],
    filetypes="ITER",
    quantities=["T_surf", "c_surf", "inventory"])
plt.show()
```
![image](https://user-images.githubusercontent.com/40028739/123226273-cbf5be80-d4d3-11eb-8d2b-a3947ff4d1c4.png)

**Comment by RemDelaporteMathurin** [comment]
a current workaround is simply to remove the legend box afterwards:
```python
from divHretention import plot_along_divertor
import matplotlib.pyplot as plt
filename = "examples/ITER/2399/2399_outer_target.csv"
plot_along_divertor(
    filenames=[filename],
    filetypes="ITER",
    quantities=["T_surf", "c_surf", "inventory"])

# remove the legend
plt.gca().get_legend().remove()

plt.show()
```

But this is inconvenient when users do need to label the cases, so it's not ideal
